### ISSUE TITLE
Incompatible with React Native 0.57

### ISSUE THREAD

**Issue by haggholm** [Kerumen/react-native-awesome-card-io#104]
Not surprising since it’s still in RC status, but:

```
> Task :react-native-awesome-card-io:compileDebugJavaWithJavac
/mnt/scratch/shared/petter/owl-devenv/client-react-native-navigation/root/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOPackage.java:13: error: RNCardIOPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNCardIOPackage implements ReactPackage {
       ^
/mnt/scratch/shared/petter/owl-devenv/client-react-native-navigation/root/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:19: error: RNCardIOModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNCardIOModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/mnt/scratch/shared/petter/owl-devenv/client-react-native-navigation/root/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:102: error: method does not override or implement a method from a supertype
  @Override
  ^
/mnt/scratch/shared/petter/owl-devenv/client-react-native-navigation/root/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:124: error: method does not override or implement a method from a supertype
  @Override
  ^
4 errors
```

**Comment by danielgindi** [comment]
There's no real breaking change. What I've noticed is that after upgrading to 0.57.0 - android studio somehow compiles against a downloaded package of react 0.20.1. It just went way back.

**Comment by danielgindi** [comment]
Actually there might be some breaking change: https://github.com/react-native-community/react-native-releases/issues/34

**Comment by haggholm** [comment]
I’m not an expert on Gradle (very far from it), but it seems to me like `awesome-card-io` is built against `0.57.0-rc.0` as expected, *not* an old version. Possibly it will by default in Android Studio (I don’t use it for builds), but our build scripts enforce a consistent `react-native` version for all dependencies.

```groovy
subprojects { subproject ->
    afterEvaluate{
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            // ...
            dependencies {
                api "com.facebook.react:react-native:${rootProject.ext.reactNativeVersion}"
                api "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
            }
        }
    }
}
```


```bash
./gradlew :app:dependencies --scan
```

https://scans.gradle.com/s/edgtcdmjzap2w/dependencies?toggled=W1swXSxbMCw4XSxbMCw4LFsxNjFdXSxbMCw3XSxbMCw3LFsxNjFdXSxbMCw1XSxbMCw1LFsxNjFdXSxbMCw0XSxbMCw0LFsxNjFdXSxbMCwyXSxbMCw3LFsxNjNdXSxbMCw0LFsxNjNdXSxbMCw1LFsxNjNdXSxbMCw4LFsxNjNdXSxbMCwxMF0sWzAsMTAsWzE2M11dLFswLDEwLFsxNjFdXSxbMCwxMV0sWzAsMTEsWzE2M11dLFswLDExLFsxNjFdXSxbMCwxNV0sWzAsMTddLFswLDE3LFsxNjNdXSxbMCwxNyxbMTYxXV0sWzAsMThdLFswLDE4LFsxNjNdXSxbMCwxOCxbMTYxXV0sWzAsMjBdLFswLDIwLFsxNjNdXSxbMCwyMCxbMTYxXV0sWzAsMjFdLFswLDIxLFsxNjFdXSxbMCwyMSxbMTYzXV1d

**Comment by danielgindi** [comment]
The problem seems to have disappeared with rc.2

**Comment by mitchell-n** [comment]
I am getting the following issue when trying to use with RN 0.57.0

`:react-native-awesome-card-io:mergeReleaseConsumerProguardFiles
:react-native-awesome-card-io:transformNativeLibsWithSyncJniLibsForRelease
:react-native-awesome-card-io:mergeReleaseResources
:react-native-awesome-card-io:verifyReleaseResources
error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
/Users/Neil/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/da52e62d58625b2cb6ef39fcdaacb176/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

/Users/Neil/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/da52e62d58625b2cb6ef39fcdaacb176/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.

/Users/Neil/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/da52e62d58625b2cb6ef39fcdaacb176/res/values-v26/values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.

/Users/Neil/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/da52e62d58625b2cb6ef39fcdaacb176/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontStyle not found.

/Users/Neil/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/da52e62d58625b2cb6ef39fcdaacb176/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/font not found.

/Users/Neil/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/da52e62d58625b2cb6ef39fcdaacb176/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontWeight not found.

error: failed linking references.
:react-native-awesome-card-io:verifyReleaseResources FAILED`

**Comment by Kerumen** [comment]
I just published `0.8.0` which should fix this. Feel free to reopen if the issue persists!
