### ISSUE TITLE
error in android on build

### ISSUE THREAD

**Issue by mephisto83** [Kerumen/react-native-awesome-card-io#83]
RNCardIOPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

 "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
"react-native-awesome-card-io": "^0.7.0",

**Comment by vsrinivas150283** [comment]
0.7.0 version seems to fix this issue, when i upgraded to 0.7.0 issue got resolved. Probably you need to clean and re-install the dependencies.

**Comment by ODelibalta** [comment]
I am version 7 but I am having the same issue... 

### build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        // mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            // url "$rootDir/../node_modules/react-native/android"
            url "https://maven.google.com"
        }
        maven {
            url "https://jitpack.io" 
        }
    }
}
```

### app / build.gradle
```
dependencies {
    compile project(':react-native-version-number')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-signature-capture')
    compile project(':react-native-awesome-card-io')
    compile project(':react-native-vector-icons')
    compile project(':react-native-navigation')
    compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
    }
    compile ("com.google.android.gms:play-services-vision:10.2.0") {
        force = true;
    }
}
```

### MainApplication.java
```
 public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.<ReactPackage>asList(
      new MainReactPackage(),
      new RNVersionNumberPackage(),
      new RSSignatureCapturePackage(),
      new RNCameraPackage(),
      new RNCardIOPackage(),
      new VectorIconsPackage()
    );
  }
``` 

### package.json
```
"dependencies": {
    "axios": "^0.17.1",
    "date-fns": "^1.29.0",
    "lodash": "^4.17.4",
    "native-base": "2.3.5",
    "prop-types": "^15.6.0",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-awesome-card-io": "^0.7.0",
    "react-native-calendars": "^1.16.1",
    "react-native-camera": "^1.0.0",
    "react-native-easy-grid": "^0.1.15",
    "react-native-elements": "^0.18.0",
    "react-native-modal": "^4.1.1",
    "react-native-modal-datetime-picker": "^4.13.0",
    "react-native-navigation": "^1.1.338",
    "react-native-signature-capture": "^0.4.9",
    "react-native-vector-icons": "^4.4.2",
    "react-native-version-number": "^0.3.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0",
    "validate.js": "^0.12.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.3",
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "eslint": "^4.13.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-react": "^7.5.1",
    "eslint-plugin-react-native": "^3.2.0",
    "jest": "21.2.1",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
```

My compile output

```
:react-native-awesome-card-io:compileReleaseJavaWithJavac
:react-native-awesome-card-io:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/odelibalta/Code/vivaa/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOPackage.java:13: error: RNCardIOPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNCardIOPackage implements ReactPackage {
       ^
/Users/odelibalta/Code/vivaa/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:19: error: RNCardIOModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNCardIOModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/odelibalta/Code/vivaa/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:102: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/odelibalta/Code/vivaa/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:124: error: method does not override or implement a method from a supertype
  @Override
  ^
4 errors
:react-native-awesome-card-io:compileReleaseJavaWithJavac FAILED
```

I'd really appreciate any help. I have re-installed node modules but it did not help.

**Comment by kelokchan** [comment]
downgrade to v0.6.4 fixed the issue for me

**Comment by ralph-dev** [comment]
+1
